[package]
name = "hana-host"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace
hana-oracle.workspace = true
hana-client.workspace = true
hana-proofs.workspace = true

# Kona
kona-preimage = { workspace = true, features = ["std"] }
kona-proof = { workspace = true, features = ["std"] }
kona-providers-alloy.workspace = true
kona-std-fpvm.workspace = true
kona-genesis.workspace = true

# Alloy
alloy-provider = { workspace = true, features = ["reqwest"] }
alloy-primitives = { workspace = true, features = ["serde"] }

# Op Alloy
op-alloy-network.workspace = true


# General
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive", "env"] }
tracing-subscriber = { workspace = true, features = ["fmt"] }

# Celestia
celestia-types.workspace = true
celestia-rpc.workspace = true

kona-host.workspace = true
kona-cli.workspace = true

[dev-dependencies]
proptest.workspace = true

[features]
default = ["celestia"]
celestia = []

[[bin]]
name = "kona-host"
path = "src/bin/host.rs"

